load("@fbcode//buck2:proto_defs.bzl", "rust_protobuf_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("build_infra")

rust_protobuf_library(
    name = "buck2_event_publisher_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_event_publisher_proto.proto",
    deps = [
        "fbsource//third-party/rust:tonic",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/app/buck2_host_sharing_proto:buck2_host_sharing_proto",
    ],
)

proto_srcs(
    name = "buck2_event_publisher_proto.proto",
    srcs = ["event_publisher.proto"],
    visibility = ["PUBLIC"],
    deps = [
      translate_target("//buck2/app //buck2/app/buck2_data:data_proto"),
      translate_target("//buck2/app/buck2_host_sharing_proto:host_sharing_proto"),
    ],
)
